import { systemWeights } from 'react-native-typography';
export default {
  disabledOpacity: 0.5,
  spacing: {
    gutters: 16,
    text: 4,
    small: 8,
    medium: 12,
    large: 16,
  },
  borderRadius: {
    global: 6,
    button: 24,
  },
  colors: {
    background: 'rgba(251, 252, 253, 1)',
    divider: 'rgba(234, 237, 242, 1)',
    error: 'rgba(255, 69, 100, 1)',
    light: 'rgba(165, 173, 183, 1)',
    lightInverse: 'rgba(255, 255, 255, 0.68)',
    medium: 'rgba(70, 78, 88, 1)',
    mediumInverse: 'rgba(255, 255, 255, 0.87)',
    primary: 'rgba(90, 69, 255, 1)',
    secondary: 'rgba(59, 201, 234, 1)',
    strong: 'rgba(18, 20, 44, 1)',
    strongInverse: 'rgba(255, 255, 255, 1)',
    surface: 'rgba(255, 255, 255, 1)',
    custom_rgb134_139_145: 'rgb(134, 139, 145)',
  },
  elevation: {
    0: {
      shadowColor: 'rgba(18, 20, 44, 1)',
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowOpacity: 0,
      borderWidth: 0,
      borderColor: 'rgba(18, 20, 44, 1)',
      borderOpacity: 0,
    },
    1: {
      shadowColor: 'rgba(18, 20, 44, 1)',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowRadius: 4,
      shadowOpacity: 0.06,
      borderWidth: 1,
      borderColor: 'rgba(18, 20, 44, 1)',
      borderOpacity: 0.06,
    },
    2: {
      shadowColor: 'rgba(18, 20, 44, 1)',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowRadius: 4,
      shadowOpacity: 0.08,
      borderWidth: 0,
      borderColor: 'rgba(18, 20, 44, 1)',
      borderOpacity: 0,
    },
    3: {
      shadowColor: 'rgba(18, 20, 44, 1)',
      shadowOffset: {
        width: 0,
        height: 6,
      },
      shadowRadius: 6,
      shadowOpacity: 0.12,
      borderWidth: 0,
      borderColor: 'rgba(18, 20, 44, 1)',
      borderOpacity: 0,
    },
  },
  typography: {
    body1: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 26,
    },
    body2: {
      ...systemWeights.regular,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 22,
    },
    button: {
      ...systemWeights.bold,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 16,
    },
    caption: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom14: {
      ...systemWeights.regular,
      fontSize: 10,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom15: {
      ...systemWeights.regular,
      fontSize: 10,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom16: {
      ...systemWeights.regular,
      fontSize: 8,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom17: {
      ...systemWeights.regular,
      fontSize: 8,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom18: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 34,
    },
    custom19: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 34,
    },
    custom20: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 34,
    },
    custom21: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 34,
    },
    custom22: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 34,
    },
    custom23: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 34,
    },
    custom24: {
      ...systemWeights.regular,
      fontSize: 8,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom25: {
      ...systemWeights.regular,
      fontSize: 1,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom26: {
      ...systemWeights.regular,
      fontSize: 10,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom27: {
      ...systemWeights.regular,
      fontSize: 10,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom28: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom29: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom30: {
      fontFamily: 'MerriweatherBold',
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom31: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom32: {
      ...systemWeights.regular,
      fontSize: 2,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom33: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom33: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom35: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom36: {
      ...systemWeights.regular,
      fontSize: 1,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom37: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom38: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom39: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom40: {
      ...systemWeights.bold,
      fontSize: 34,
      letterSpacing: 0,
      lineHeight: 0,
    },
    custom41: {
      ...systemWeights.bold,
      fontSize: 34,
      letterSpacing: 0,
      lineHeight: 0,
    },
    custom42: {
      ...systemWeights.bold,
      fontSize: 34,
      letterSpacing: 0,
      lineHeight: 40,
    },
    custom43: {
      ...systemWeights.bold,
      fontSize: 34,
      letterSpacing: 0,
      lineHeight: 40,
    },
    custom44: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 26,
    },
    custom45: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom46: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom47: {
      ...systemWeights.semibold,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 26,
    },
    custom48: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 26,
    },
    custom49: {
      ...systemWeights.bold,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom50: {
      ...systemWeights.bold,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom51: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom52: {
      ...systemWeights.bold,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom53: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 26,
    },
    headline1: {
      ...systemWeights.bold,
      fontSize: 60,
      letterSpacing: 0,
      lineHeight: 71,
    },
    headline2: {
      ...systemWeights.bold,
      fontSize: 48,
      letterSpacing: 0,
      lineHeight: 58,
    },
    headline3: {
      ...systemWeights.bold,
      fontSize: 34,
      letterSpacing: 0,
      lineHeight: 40,
    },
    headline4: {
      ...systemWeights.bold,
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 34,
    },
    headline5: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 0,
      lineHeight: 26,
    },
    headline6: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 24,
    },
    overline: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 2,
      lineHeight: 16,
    },
    subtitle1: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 26,
    },
    subtitle2: {
      ...systemWeights.regular,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 22,
    },
  },
};
